### ISSUE TITLE
[NutScript 1.1] Unknown 

### ISSUE THREAD

**Issue by art-gur** [Chessnut/NutScript#392] opened 2015-03-16 13:10 UTC
When a player writes in chat / me action, other players see it this way:
unknown welcome you.

Also, people see the staff of civil defense as strangers and employees of civil defense did not see each other in the scoreboard.

**Comment by Chessnut** [comment] 2015-03-17 18:32
Duplicate of #356.

**Closed by Chessnut** 2015-03-17 18:32 UTC
