### ISSUE TITLE
[1.1]Weapon ammo isn't saved on server restart

### ISSUE THREAD

**Issue by koen24** [Chessnut/NutScript#553] opened 2015-07-17 19:18 UTC
Whenever ammo is loaded (and not in a gun's first clip), it will dissappear when the server restarts.

**Comment by Chessnut** [comment] 2015-07-17 21:45
Duplicate of #472

**Comment by koen24** [comment] 2015-07-18 12:07
It isn't the same issue. #472 only regards the first clip of ammo (the amount that's already loaded into the gun)
Imagine I have a revolver. I load a box of 12 rounds and load my gun. The revolver would have 6 rounds in it and 6 extra rounds. With this issue, it's the extra rounds that disappear, not the rounds that have already been loaded into the gun. Besides, #472 occurs when the player respawns, or the character is reloaded. This bug only occurs whenever the server is restarted.

**Comment by Chessnut** [comment] 2015-07-18 16:55
Well if the issue is when the server is restarted, it seems like it is not a clean restart as the CharacterPreSave hook is not being ran.

**Comment by koen24** [comment] 2015-07-18 17:32
Just repeated my steps on a clean install of both nutscript and the hl2rp schema and made sure I shut down the server properly by typing 'quit' in the console, but the issue persists.

**Comment by Thadah** [comment] 2015-07-20 22:28
Confirming.

Steps to reproduce:
1. Spawn a vendor
2. Buy gun and buy ammo
3. Equip gun and load ammo
4. Shoot once
5. Reload the gun (to change the amount on the secondary magazine mostly)
6. `quit` the server

When restarting the server and going in, only first clip is full, the extra ammo is gone.

**Comment by Chessnut** [comment] 2015-07-21 03:18
So I got that fixed, but for some reason the remaining ammo won't save. For some reason, setting the ammo count won't stay.

**Closed as completed** 2015-07-21 22:01 UTC
