### ISSUE TITLE
[Suggestion] Weapons on back

### ISSUE THREAD

**Issue by maxyii** [Chessnut/NutScript#504] opened 2015-06-13 12:29 UTC
If there is someone with a plugin they can send to me with a feature where all weapons equipped appear on the players back, that would be great.

**Comment by Trixas** [comment] 2015-06-18 13:55
I'm pretty sure modernRP do have it

**Comment by Chessnut** [comment] 2015-06-23 23:29
Turns out Black Tea added a HOLSTER_DRAWINFO table that you use like:
`HOLSTER_DRAWINFO["weapon_pistol"] = {bone = "bone here", pos = Vector(1, 2, 3), ang = Angle(1, 2, 3)`

So one just needs to set this up for the desired weapon.

**Comment by Chessnut** [comment] 2015-06-26 00:26
Closed. Duplicate of #353.

**Closed as completed by Chessnut** 2015-06-26 00:26 UTC
