### ISSUE TITLE
"Loading" screen bug

### ISSUE THREAD

**Issue by OmniSyzygy** [Chessnut/NutScript#459] opened 2015-04-18 17:13 UTC
Same as with issue #420 Except no longer does it spam console with MySQL error. It seems overnight, and you have to restart the server. As long as players are on the server, it doesn't error out, but when no one is on for about 6-8 hours (Notorious in the morning once people wake up) it shows this.

**Comment by blt950** [comment] 2015-06-11 21:51
I had this bug as well, fixed easily by switching over to tmysql instead of mysqloo module.

**Comment by Chessnut** [comment] 2015-06-11 22:07
Duplicate of #466

**Closed as completed by Chessnut** 2015-06-11 22:07 UTC
