### ISSUE TITLE
Icon Error

### ISSUE THREAD

**Issue by Demersuss** [Chessnut/NutScript#488] opened 2015-05-31 20:24 UTC
Once again, sorry for the lack of lua knowledge. Not sure if this is a quick fix on my part but -
Looks like the same type of error I posted a couple hours ago. Am I doing something wrong?

[ERROR] gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:105: bad argument #2 to 'L' (no value)
1. L - [C]:-1
   1. setInventory - gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:105
   2. callback - gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:401
      1. DoClick - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:171
      2. unknown - lua/vgui/dlabel.lua:218

**Comment by Chessnut** [comment] 2015-05-31 21:47
This is a duplicate of #481. Next time check if an issue already exists. We don't need more than 1 of the same issue being reported.

**Closed as completed by Chessnut** 2015-05-31 21:47 UTC
