### ISSUE TITLE
[NutScript 1.1] Radio no text

### ISSUE THREAD

**Issue by art-gur** [Chessnut/NutScript#402] opened 2015-03-19 11:26 UTC
When you send messages through the radio, no messages can be seen chatting and interlocutor does not see them.

**Comment by DeadiKation** [comment] 2015-03-19 19:36
No errors are present in console either.

**Comment by Chessnut** [comment] 2015-03-19 23:34
Duplicate of Chessnut/hl2rp#62

**Closed by Chessnut** 2015-03-19 23:34 UTC
